/**
 * projects-data.js
 * Single source of truth for both the listing page (projects.html)
 * and the single project page (project-detail.html).
 *
 * status: 'ongoing' | 'completed'  -> listing badge + status filter
 * location / year                  -> listing sidebar filters
 * startDate / endDate / country /
 * organization / budget / description / lat / lng -> detail page only
 */
const projectsData = [
  {
    id: 1,
    status: 'ongoing',
    image: 'clients/Project1.jpg',
    title: 'Fisheries Livelihood Enhancement Project in the Coastal Area of the Bay of Bengal (FiLEP-LNC)',
    location: 'Cox\'s Bazar',
    year: 2024,
    startDate: '10.02.2024',
    endDate: '10.02.2026',
    country: 'Bangladesh',
    organization: 'NACOM',
    budget: '$109,540.95',
    lat: 21.4272,
    lng: 92.0058,
    description: 'FiLEP-LNC works with fishing communities along the Bay of Bengal coastline to improve livelihoods through sustainable fisheries management, alternative income training, and better access to markets. The project also supports local cooperatives in adopting practices that protect fish stocks for the long term while easing pressure on households that depend on daily catch for income.',
  },
  {
    id: 2,
    status: 'ongoing',
    image: 'clients/project2.jpg',
    title: 'Primary Scientific, Socio-Economic, and Cadastral Assessment for the Declaration of Nine Areas in Sylhet',
    location: 'Sylhet',
    year: 2024,
    startDate: '03.03.2024',
    endDate: '03.03.2026',
    country: 'Bangladesh',
    organization: 'NACOM',
    budget: '$142,300.00',
    lat: 24.8949,
    lng: 91.8687,
    description: 'This assessment combines ecological survey work, socio-economic profiling, and cadastral mapping to support the formal declaration of nine ecologically significant areas in Sylhet. Findings will feed directly into conservation planning and inform land-use decisions made with local communities and government partners.',
  },
  {
    id: 3,
    status: 'completed',
    image: 'clients/project3.jpeg',
    title: 'Cleaner Air, Healthier Dhaka: Enhancing Air Quality Monitoring & Public Awareness in DNCC',
    location: 'Dhaka',
    year: 2023,
    startDate: '01.06.2022',
    endDate: '30.11.2023',
    country: 'Bangladesh',
    organization: 'Pure Earth Bangladesh',
    budget: '$109,540.95',
    lat: 23.8103,
    lng: 90.4125,
    description: 'The project installed low-cost air quality sensors across Dhaka North City Corporation and ran a public awareness campaign on the health effects of air pollution. Real-time data was shared with residents and city officials to support targeted mitigation policies in the highest-exposure neighborhoods.',
  },
  {
    id: 4,
    status: 'completed',
    image: 'https://images.unsplash.com/photo-1542810634-71277d95dcbb?q=80&w=800&auto=format&fit=crop',
    title: 'Food Security Program for Coastal Farming Communities',
    location: 'Barisal',
    year: 2023,
    startDate: '12.02.2023',
    endDate: '20.12.2023',
    country: 'Bangladesh',
    organization: 'NACOM',
    budget: '$96,750.00',
    lat: 22.7010,
    lng: 90.3535,
    description: 'Working with smallholder farming households in coastal Barisal, this program distributed climate-resilient seed varieties and ran agricultural training to help families maintain stable harvests despite increasing soil salinity and unpredictable rainfall.',
  },
  {
    id: 5,
    status: 'ongoing',
    image: 'https://images.unsplash.com/photo-1574482620811-1aa16ffe3c82?q=80&w=800&auto=format&fit=crop',
    title: 'Women Empowerment Through Sustainable Livelihoods',
    location: 'Rajshahi',
    year: 2025,
    startDate: '15.01.2025',
    endDate: '15.01.2027',
    country: 'Bangladesh',
    organization: 'NACOM',
    budget: '$78,200.00',
    lat: 24.3745,
    lng: 88.6042,
    description: 'This initiative provides vocational training and micro-finance access to women in Rajshahi, helping them build independent, sustainable income sources through small-scale enterprise and cooperative farming ventures.',
  },
  {
    id: 6,
    status: 'completed',
    image: 'https://images.unsplash.com/photo-1532629345422-7515f3d16bb6?q=80&w=800&auto=format&fit=crop',
    title: 'Medical Aid Outreach for Isolated Rural Villages',
    location: 'Khulna',
    year: 2022,
    startDate: '05.08.2022',
    endDate: '05.02.2023',
    country: 'Bangladesh',
    organization: 'Pure Earth Bangladesh',
    budget: '$64,900.00',
    lat: 22.8456,
    lng: 89.5403,
    description: 'Mobile medical units delivered essential medicines, maternal care, and basic health screenings to villages in Khulna that lack reliable access to healthcare facilities, reaching several thousand residents over the course of the program.',
  },
  {
    id: 7,
    status: 'ongoing',
    image: 'https://images.unsplash.com/photo-1542810634-71277d95dcbb?q=80&w=800&auto=format&fit=crop',
    title: 'Mangrove Restoration and Coastal Resilience Initiative',
    location: 'Khulna',
    year: 2025,
    startDate: '04.04.2025',
    endDate: '04.04.2028',
    country: 'Bangladesh',
    organization: 'NACOM',
    budget: '$187,400.00',
    lat: 22.5000,
    lng: 89.4000,
    description: 'This initiative replants degraded mangrove belts along the Khulna coastline to restore natural storm buffers and fish nursery habitat, working with local communities on long-term stewardship and monitoring.',
  },
  {
    id: 8,
    status: 'completed',
    image: 'https://images.unsplash.com/photo-1574482620811-1aa16ffe3c82?q=80&w=800&auto=format&fit=crop',
    title: 'Groundwater Quality Monitoring & Community Training',
    location: 'Rajshahi',
    year: 2023,
    startDate: '10.09.2023',
    endDate: '10.03.2024',
    country: 'Bangladesh',
    organization: 'NACOM',
    budget: '$52,300.00',
    lat: 24.4000,
    lng: 88.5500,
    description: 'The project set up a groundwater quality monitoring network across Rajshahi and trained community volunteers to collect and report data, building a long-term picture of arsenic and salinity levels in local drinking water.',
  },
];